/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnitsIndexRouteImport } from './routes/units/index'
import { Route as IngredientsIndexRouteImport } from './routes/ingredients/index'
import { Route as UnitsNewRouteImport } from './routes/units/new'
import { Route as IngredientsNewRouteImport } from './routes/ingredients/new'
import { Route as DemoWorkosRouteImport } from './routes/demo/workos'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'
import { Route as UnitsIdIndexRouteImport } from './routes/units/$id/index'
import { Route as IngredientsIdIndexRouteImport } from './routes/ingredients/$id/index'
import { Route as UnitsIdEditRouteImport } from './routes/units/$id/edit'
import { Route as IngredientsIdEditRouteImport } from './routes/ingredients/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsIndexRoute = UnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIndexRoute = IngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsNewRoute = UnitsNewRouteImport.update({
  id: '/units/new',
  path: '/units/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsNewRoute = IngredientsNewRouteImport.update({
  id: '/ingredients/new',
  path: '/ingredients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoWorkosRoute = DemoWorkosRouteImport.update({
  id: '/demo/workos',
  path: '/demo/workos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsIdIndexRoute = UnitsIdIndexRouteImport.update({
  id: '/units/$id/',
  path: '/units/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIdIndexRoute = IngredientsIdIndexRouteImport.update({
  id: '/ingredients/$id/',
  path: '/ingredients/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsIdEditRoute = UnitsIdEditRouteImport.update({
  id: '/units/$id/edit',
  path: '/units/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIdEditRoute = IngredientsIdEditRouteImport.update({
  id: '/ingredients/$id/edit',
  path: '/ingredients/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/units/new': typeof UnitsNewRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/units/': typeof UnitsIndexRoute
  '/ingredients/$id/edit': typeof IngredientsIdEditRoute
  '/units/$id/edit': typeof UnitsIdEditRoute
  '/ingredients/$id/': typeof IngredientsIdIndexRoute
  '/units/$id/': typeof UnitsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/units/new': typeof UnitsNewRoute
  '/ingredients': typeof IngredientsIndexRoute
  '/units': typeof UnitsIndexRoute
  '/ingredients/$id/edit': typeof IngredientsIdEditRoute
  '/units/$id/edit': typeof UnitsIdEditRoute
  '/ingredients/$id': typeof IngredientsIdIndexRoute
  '/units/$id': typeof UnitsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/units/new': typeof UnitsNewRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/units/': typeof UnitsIndexRoute
  '/ingredients/$id/edit': typeof IngredientsIdEditRoute
  '/units/$id/edit': typeof UnitsIdEditRoute
  '/ingredients/$id/': typeof IngredientsIdIndexRoute
  '/units/$id/': typeof UnitsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/convex'
    | '/demo/workos'
    | '/ingredients/new'
    | '/units/new'
    | '/ingredients/'
    | '/units/'
    | '/ingredients/$id/edit'
    | '/units/$id/edit'
    | '/ingredients/$id/'
    | '/units/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/convex'
    | '/demo/workos'
    | '/ingredients/new'
    | '/units/new'
    | '/ingredients'
    | '/units'
    | '/ingredients/$id/edit'
    | '/units/$id/edit'
    | '/ingredients/$id'
    | '/units/$id'
  id:
    | '__root__'
    | '/'
    | '/demo/convex'
    | '/demo/workos'
    | '/ingredients/new'
    | '/units/new'
    | '/ingredients/'
    | '/units/'
    | '/ingredients/$id/edit'
    | '/units/$id/edit'
    | '/ingredients/$id/'
    | '/units/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoConvexRoute: typeof DemoConvexRoute
  DemoWorkosRoute: typeof DemoWorkosRoute
  IngredientsNewRoute: typeof IngredientsNewRoute
  UnitsNewRoute: typeof UnitsNewRoute
  IngredientsIndexRoute: typeof IngredientsIndexRoute
  UnitsIndexRoute: typeof UnitsIndexRoute
  IngredientsIdEditRoute: typeof IngredientsIdEditRoute
  UnitsIdEditRoute: typeof UnitsIdEditRoute
  IngredientsIdIndexRoute: typeof IngredientsIdIndexRoute
  UnitsIdIndexRoute: typeof UnitsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/': {
      id: '/units/'
      path: '/units'
      fullPath: '/units/'
      preLoaderRoute: typeof UnitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/': {
      id: '/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof IngredientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/new': {
      id: '/units/new'
      path: '/units/new'
      fullPath: '/units/new'
      preLoaderRoute: typeof UnitsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/new': {
      id: '/ingredients/new'
      path: '/ingredients/new'
      fullPath: '/ingredients/new'
      preLoaderRoute: typeof IngredientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/workos': {
      id: '/demo/workos'
      path: '/demo/workos'
      fullPath: '/demo/workos'
      preLoaderRoute: typeof DemoWorkosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/$id/': {
      id: '/units/$id/'
      path: '/units/$id'
      fullPath: '/units/$id/'
      preLoaderRoute: typeof UnitsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$id/': {
      id: '/ingredients/$id/'
      path: '/ingredients/$id'
      fullPath: '/ingredients/$id/'
      preLoaderRoute: typeof IngredientsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/$id/edit': {
      id: '/units/$id/edit'
      path: '/units/$id/edit'
      fullPath: '/units/$id/edit'
      preLoaderRoute: typeof UnitsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$id/edit': {
      id: '/ingredients/$id/edit'
      path: '/ingredients/$id/edit'
      fullPath: '/ingredients/$id/edit'
      preLoaderRoute: typeof IngredientsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoConvexRoute: DemoConvexRoute,
  DemoWorkosRoute: DemoWorkosRoute,
  IngredientsNewRoute: IngredientsNewRoute,
  UnitsNewRoute: UnitsNewRoute,
  IngredientsIndexRoute: IngredientsIndexRoute,
  UnitsIndexRoute: UnitsIndexRoute,
  IngredientsIdEditRoute: IngredientsIdEditRoute,
  UnitsIdEditRoute: UnitsIdEditRoute,
  IngredientsIdIndexRoute: IngredientsIdIndexRoute,
  UnitsIdIndexRoute: UnitsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
