/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IngredientsRouteImport } from './routes/ingredients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MealPlansIndexRouteImport } from './routes/meal-plans/index'
import { Route as DishesIndexRouteImport } from './routes/dishes/index'
import { Route as ShoppingListsListIdRouteImport } from './routes/shopping-lists/$listId'
import { Route as MealPlansPlanIdRouteImport } from './routes/meal-plans/$planId'
import { Route as DishesDishIdRouteImport } from './routes/dishes/$dishId'
import { Route as DemoWorkosRouteImport } from './routes/demo/workos'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'

const IngredientsRoute = IngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlansIndexRoute = MealPlansIndexRouteImport.update({
  id: '/meal-plans/',
  path: '/meal-plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const DishesIndexRoute = DishesIndexRouteImport.update({
  id: '/dishes/',
  path: '/dishes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListsListIdRoute = ShoppingListsListIdRouteImport.update({
  id: '/shopping-lists/$listId',
  path: '/shopping-lists/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlansPlanIdRoute = MealPlansPlanIdRouteImport.update({
  id: '/meal-plans/$planId',
  path: '/meal-plans/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const DishesDishIdRoute = DishesDishIdRouteImport.update({
  id: '/dishes/$dishId',
  path: '/dishes/$dishId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoWorkosRoute = DemoWorkosRouteImport.update({
  id: '/demo/workos',
  path: '/demo/workos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ingredients': typeof IngredientsRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/dishes/$dishId': typeof DishesDishIdRoute
  '/meal-plans/$planId': typeof MealPlansPlanIdRoute
  '/shopping-lists/$listId': typeof ShoppingListsListIdRoute
  '/dishes/': typeof DishesIndexRoute
  '/meal-plans/': typeof MealPlansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ingredients': typeof IngredientsRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/dishes/$dishId': typeof DishesDishIdRoute
  '/meal-plans/$planId': typeof MealPlansPlanIdRoute
  '/shopping-lists/$listId': typeof ShoppingListsListIdRoute
  '/dishes': typeof DishesIndexRoute
  '/meal-plans': typeof MealPlansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ingredients': typeof IngredientsRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/dishes/$dishId': typeof DishesDishIdRoute
  '/meal-plans/$planId': typeof MealPlansPlanIdRoute
  '/shopping-lists/$listId': typeof ShoppingListsListIdRoute
  '/dishes/': typeof DishesIndexRoute
  '/meal-plans/': typeof MealPlansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ingredients'
    | '/demo/convex'
    | '/demo/workos'
    | '/dishes/$dishId'
    | '/meal-plans/$planId'
    | '/shopping-lists/$listId'
    | '/dishes/'
    | '/meal-plans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ingredients'
    | '/demo/convex'
    | '/demo/workos'
    | '/dishes/$dishId'
    | '/meal-plans/$planId'
    | '/shopping-lists/$listId'
    | '/dishes'
    | '/meal-plans'
  id:
    | '__root__'
    | '/'
    | '/ingredients'
    | '/demo/convex'
    | '/demo/workos'
    | '/dishes/$dishId'
    | '/meal-plans/$planId'
    | '/shopping-lists/$listId'
    | '/dishes/'
    | '/meal-plans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IngredientsRoute: typeof IngredientsRoute
  DemoConvexRoute: typeof DemoConvexRoute
  DemoWorkosRoute: typeof DemoWorkosRoute
  DishesDishIdRoute: typeof DishesDishIdRoute
  MealPlansPlanIdRoute: typeof MealPlansPlanIdRoute
  ShoppingListsListIdRoute: typeof ShoppingListsListIdRoute
  DishesIndexRoute: typeof DishesIndexRoute
  MealPlansIndexRoute: typeof MealPlansIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ingredients': {
      id: '/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plans/': {
      id: '/meal-plans/'
      path: '/meal-plans'
      fullPath: '/meal-plans/'
      preLoaderRoute: typeof MealPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dishes/': {
      id: '/dishes/'
      path: '/dishes'
      fullPath: '/dishes/'
      preLoaderRoute: typeof DishesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-lists/$listId': {
      id: '/shopping-lists/$listId'
      path: '/shopping-lists/$listId'
      fullPath: '/shopping-lists/$listId'
      preLoaderRoute: typeof ShoppingListsListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plans/$planId': {
      id: '/meal-plans/$planId'
      path: '/meal-plans/$planId'
      fullPath: '/meal-plans/$planId'
      preLoaderRoute: typeof MealPlansPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dishes/$dishId': {
      id: '/dishes/$dishId'
      path: '/dishes/$dishId'
      fullPath: '/dishes/$dishId'
      preLoaderRoute: typeof DishesDishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/workos': {
      id: '/demo/workos'
      path: '/demo/workos'
      fullPath: '/demo/workos'
      preLoaderRoute: typeof DemoWorkosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IngredientsRoute: IngredientsRoute,
  DemoConvexRoute: DemoConvexRoute,
  DemoWorkosRoute: DemoWorkosRoute,
  DishesDishIdRoute: DishesDishIdRoute,
  MealPlansPlanIdRoute: MealPlansPlanIdRoute,
  ShoppingListsListIdRoute: ShoppingListsListIdRoute,
  DishesIndexRoute: DishesIndexRoute,
  MealPlansIndexRoute: MealPlansIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
